-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg0IO58Sos5IA5jpQG
tlnl/Pi8aSMOFL5HjehPJJ9tC9CgCgYIKoZIzj0DAQehRANCAARjT7ybMRleQy+1
ZtavCXl5AS/U7DQteql8LCQrEk9ztx/5tDaF/aNMSl5EZ8HrcZG4lMF+bsH4lodr
LwoqlObl
-----END PRIVATE KEY-----